version: '3'

services:
  mysql-docker-container:
    image: mysql:latest
    restart: always
    command:
      --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=springmvc
      - MYSQL_DATABASE=spring_app_db
      - MYSQL_USER=pokemon
      - MYSQL_PASSWORD=pokemon
    volumes:
      - /data/mysql
    networks:
      - mynetwork
  spring-boot-jpa-app:
    image: spring-boot-jpa-image
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - WAIT_HOSTS=mysql-docker-container:3306
    ports:
      - "8087:8080"
    volumes:
      - /data/spring-boot-app
    networks:
      - mynetwork
networks:
  mynetwork: